#Mail
spring:
  data:
    redis:
      host: redis
      port: 6379

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            trust: '*'
          timeout: '3000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: '587'

mail:
  template:
    path:
      user: templates/msg_for_user.html
      museum: templates/msg_for_museum.html
  museum:
    email: museum@gmail.com
    label: Museum.ua

logging:
  file:
    name: logfile.log
  pattern:
    file: "%replace(%msg){'\\u001B\\[[;\\d]*m', ''}%n"
  level:
    root: error

resources:
  files:
    images:
      root: 'images'
      original: 'original'
      compressed: 'compressed'
      temporary: 'temp'
