#Mail
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            trust: '*'
          timeout: '3000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: '587'
