uploads:
  path: /uploads

prefix:
  response: /picture
  cache: /pictureCache

dir:
  temp: /temp
  original: /original
  preview: /preview

spring:
  servlet:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB